Fix translations
xuhuisheng/sonar-l10n-zh pull request #55
Opened 2022-08-18 11:12 UTC by kuoruan

对照 https://github.com/SonarSource/sonarqube/blob/9.6.0.59041/sonar-core/src/main/resources/org/sonar/l10n/core.properties

修改了一些不正确的翻译，调整了翻译格式

2022-10-19 03:11 UTC, kuoruan commented
![image](https://user-images.githubusercontent.com/8685618/196588549-1343353a-ce23-4207-8cb2-e82a18678517.png)

2022-10-19 03:22 UTC, xuhuisheng commented
改了换行之后，diff里看不到具体改了什么地方了

2022-10-19 03:25 UTC, kuoruan commented
换行符还是推荐使用 LF
看不到是因为整个文件都改了，Github 上加载不出来
我更新一下 patch

2022-10-19 03:37 UTC, xuhuisheng commented
要不就分两步，一步先看改了哪些内容，第二步咱们再统一改换行符。

2022-10-19 03:38 UTC, kuoruan commented
> 要不就分两步，一步先看改了哪些内容，第二步咱们再统一改换行符。

对，我就是这么想的，我稍后改一下

2022-10-19 07:30 UTC, kuoruan commented
@xuhuisheng Done，麻烦 Review 一下，调整了许多翻译，例如：“复审” -> “审查”

2022-10-19 08:05 UTC, kuoruan commented
See：https://github.com/mzlogin/chinese-copywriting-guidelines

推荐这么做

2022-10-19 08:10 UTC, xuhuisheng commented
@xuhuisheng 好吧，还真有文档。以后尽量按照这里的建议翻译。

2022-10-20 03:13 UTC, kuoruan commented
![image](https://user-images.githubusercontent.com/8685618/196847836-3baa4085-0fb0-413b-936c-23fa8b8675b2.png)

2022-10-20 03:52 UTC, kuoruan commented
先改这么多，后面发现新问题的时候再提交新的

2022-10-20 04:04 UTC, xuhuisheng commented
@kuoruan 看一下我提的几个问题。

2022-10-20 05:26 UTC, kuoruan commented
哪里？没见着

2022-10-20 08:03 UTC, xuhuisheng commented
@kuoruan 往上翻一下，提了几个review

2022-10-20 08:09 UTC, kuoruan commented
![image](https://user-images.githubusercontent.com/8685618/196892585-ca4c0115-740b-4cc9-af4f-bfb971bc4a43.png)

Show Comments 已经勾上了，一直没有看到任何 Review 评论

2022-10-20 08:22 UTC, xuhuisheng commented
![Screenshot from 2022-10-20 16-21-43](https://user-images.githubusercontent.com/1118508/196895827-3e6b1342-3362-4e69-8728-02be28db3425.png)

2022-10-20 08:26 UTC, kuoruan commented
看看是不是没有提交，我这里确实看不到。。可以开个隐私窗口看看

2022-10-20 21:38 UTC, xuhuisheng commented
@kuoruan 我这边看到的github的网页的整个截屏，难道咱们俩看到的网页内容还不一样了？奇怪哟。
![canvas](https://user-images.githubusercontent.com/1118508/197063777-4e65eb40-b0c3-49f0-b955-9197b0790be4.png)

2022-10-21 01:16 UTC, kuoruan commented
![image](https://user-images.githubusercontent.com/8685618/197088567-82f241bd-3a06-4195-b6d6-5ac20c9158b3.png)
现在的状态是 pending，是否提交了？
![image](https://user-images.githubusercontent.com/8685618/197088622-b40e7ae7-c1d7-4d68-a8e5-bb3ac015869d.png)

2022-10-21 02:28 UTC, xuhuisheng commented
@kuoruan 
木有request changes呀，莫非是我们这些没付费用户，没有高级功能？之前都是直接加comment就行了。
![Screenshot from 2022-10-21 10-26-54](https://user-images.githubusercontent.com/1118508/197097053-b1b69cbf-f148-4def-8dcb-431a644b5873.png)

2022-10-21 02:31 UTC, kuoruan commented
![image](https://user-images.githubusercontent.com/8685618/197097383-d1f409d7-7ed4-4f8c-bbab-a75316eb49c7.png)
不提交确实看不到

2022-10-21 02:58 UTC, xuhuisheng requested changes

2022-10-21 02:58 UTC, xuhuisheng commented on src/main/resources/org/sonar/l10n/core_zh.properties
> +hotspots.review_history.comment_added=添加了一个评论
一条

2022-10-21 02:58 UTC, xuhuisheng commented on src/main/resources/org/sonar/l10n/core_zh.properties
> +hotspots.status_option.FIXED.description=代码已经过审查和修改，以遵循推荐的安全编码实践。
已遵循

2022-10-21 02:58 UTC, xuhuisheng commented on src/main/resources/org/sonar/l10n/core_zh.properties
> +hotspots.find_in_status_filter_x= 你可以修改状态条件为 {status_label} 来再次找到此数据。
“你”之前的空格应该去掉吧？

2022-10-21 02:58 UTC, xuhuisheng commented on src/main/resources/org/sonar/l10n/core_zh.properties
> +onboarding.analysis.sq_scanner.execute=在你的电脑上 e 执行 SonarQube 扫描
这行应该是打错了，原文是“Execute the Scanner”，只保留“执行扫描器”就可以

2022-10-21 02:59 UTC, kuoruan commented on src/main/resources/org/sonar/l10n/core_zh.properties
> +hotspots.review_history.comment_added=添加了一个评论
现在可以看到了

2022-10-21 03:04 UTC, kuoruan commented on src/main/resources/org/sonar/l10n/core_zh.properties
> +hotspots.find_in_status_filter_x= 你可以修改状态条件为 {status_label} 来再次找到此数据。
https://github.com/SonarSource/sonarqube/blob/ff445e4ca63799153f063764f9fcc4d98671353d/sonar-core/src/main/resources/org/sonar/l10n/core.properties#L789

原句前面有个空格，暂时没找到该句的具体位置，先删除空格吧

2022-10-21 03:19 UTC, xuhuisheng commented
@kuoruan 
没问题的话， 就merge啦。

2022-10-21 03:20 UTC, kuoruan commented
c7c9d29b5ef5ba87f82a57a514435e40f2210d56 这条提交故意讲 LF 改为了 CRLF，出于什么考虑呢？

2022-10-21 03:23 UTC, kuoruan commented
> @kuoruan 没问题的话， 就merge啦。

Merge 的时候麻烦选一下 Squash Merge

2022-10-21 03:25 UTC, xuhuisheng commented
> [c7c9d29](https://github.com/xuhuisheng/sonar-l10n-zh/commit/c7c9d29b5ef5ba87f82a57a514435e40f2210d56) 这条提交故意讲 LF 改为了 CRLF，出于什么考虑呢？

比较早了，应该是当时懒得驳回修改了，所以就merge了，以后有标准了就好，我会把你发的文档建议附加到readme了，供以后参考。

2022-10-21 03:26 UTC, merged